version: "3.6"
volumes:
  db:
networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28

services:
  &db-service mysql:
    container_name: ${MYSQL_HOST}
    hostname: ${MYSQL_HOST}
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      web:

  &apache-php httpd:
    container_name: "${APACHE_CONTAINER_NAME}"
    hostname: "${APACHE_CONTAINER_NAME}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    depends_on:
      - *db-service
    build:
      dockerfile: Dockerfile
      context: ./Docker
    environment:
      SITE_DOMAIN: "${SITE_DOMAIN}"
      APACHE_RUN_USER: "${CURRENT_USER}"
      APACHE_RUN_GROUP: "${CURRENT_USER_GROUP}"
      CURRENT_USER: "${CURRENT_USER}"
      CURRENT_USER_ID: "${CURRENT_USER_ID}"
      CURRENT_USER_GROUP: "${CURRENT_USER_GROUP}"
      CURRENT_USER_GROUP_ID: "${CURRENT_USER_GROUP_ID}"
      PHP_IDE_CONFIG: "serverName=Docker"
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html:rw
      - ./Docker/dev/httpd.conf:/etc/apache2/apache2.conf:ro
      - ./Docker/dev/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./Docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./Docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      web:

  &pma-service phpmyadmin:
    container_name: *pma-service
    hostname: *pma-service
    restart: always
    image: phpmyadmin
    links:
      - *db-service
    depends_on:
      - *db-service
    ports:
      - ${PHPMYADMIN_CONTAINER_PORT}:80
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: "1G"
    networks:
      web:

