version: '3.0'
networks:
  forum:

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
      - php-cli
    networks:
      - forum


  php-fpm:
    build:
      context: ./docker/php-fpm
    restart: always
    volumes:
      - ./app:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    ports:
      - "9001:9001"
    depends_on:
      - mysql
    networks:
      - forum


  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./app:/symfony
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli
    networks:
      - forum

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - forum



volumes:
  mysql: